// Editorial source. Keep claims grounded in the approved offer and published projects.
export const communes = ['Castro','Ancud','Chonchi','Curaco de Vélez','Dalcahue','Puqueldón','Queilén','Quellón','Quemchi','Quinchao'];
export const pages = [
  {
    path:'/servicios/diseno-web/', section:'Servicios', title:'Diseño y desarrollo de páginas web para empresas | Bergerac',
    heading:'Una web que explique bien lo que haces.',
    description:'Diseño y desarrollo web para empresas y profesionales. En Bergerac estudiamos tu negocio, ordenamos el contenido y construimos un sitio propio desde Castro, Chiloé.',
    lead:'Diseñamos y desarrollamos páginas web para empresas y profesionales. Partimos por entender tu negocio: qué ofreces, a quién te diriges y qué necesita saber una persona antes de contactarte.',
    blocks:[
      {title:'Un sitio nuevo. O una presencia que necesita cambiar.',html:'<p>Podemos comenzar desde cero o revisar una página que ya existe. El primer paso es reconocer qué vale la pena conservar y qué está dificultando que tus clientes entiendan tu oferta.</p><p>Una empresa de servicios necesita explicar sus capacidades. Un estudio de arquitectura necesita mostrar sus obras. Un profesional necesita presentar su experiencia. La estructura se define a partir de esa diferencia.</p>'},
      {title:'Qué trabajamos contigo',html:'<ul><li><strong>Dirección:</strong> revisamos tu negocio, su contexto y el objetivo de la página.</li><li><strong>Contenido:</strong> decidimos qué contar y en qué orden, para que la oferta sea comprensible.</li><li><strong>Diseño:</strong> desarrollamos una composición propia, coherente con tu marca y legible en pantallas pequeñas.</li><li><strong>Desarrollo:</strong> construimos la experiencia, sus interacciones y el camino hacia el contacto.</li><li><strong>Revisión:</strong> afinamos la propuesta contigo y comprobamos la versión que se publica.</li></ul><p>El alcance concreto queda definido en la propuesta. Integraciones, edición de contenido, mantenimiento y servicios de terceros se acuerdan según lo que necesite cada proyecto.</p>'},
      {title:'Cómo empezamos',html:'<p>Cuéntanos qué hace tu negocio, qué estás mostrando hoy y qué te gustaría conseguir. Si tienes sitio, redes sociales o referencias, compártelos. No necesitas llegar con un documento técnico ni con todas las respuestas resueltas.</p><p>Durante la primera conversación identificamos el contenido disponible, las decisiones pendientes y las personas que participarán en la revisión. Con esa información podemos proponer un alcance y un calendario realistas.</p>'},
      {title:'Precio y plazo dependen del alcance',html:'<p>Una página de presentación y un portafolio con muchos proyectos requieren trabajos distintos. También influyen los textos, las fotografías, las funciones y las revisiones necesarias. Por eso cotizamos después de entender la necesidad.</p><p>Antes de comenzar conviene dejar por escrito qué se entregará, qué aportará el cliente, cómo se revisará el trabajo y qué gastos continuarán después de la publicación. Puedes leer nuestra <a href="/guias/cuanto-cuesta-una-pagina-web/">guía para comparar presupuestos web</a>.</p>'},
      {title:'Desde Castro, para negocios de Chiloé',html:'<p>Bergerac es un estudio digital en Castro, Chiloé. Si tu negocio está en otra comuna del archipiélago, podemos comenzar compartiendo tu situación a través del formulario y acordar la primera reunión.</p><p><a href="/diseno-web-chiloe/">Conoce nuestra cobertura en Chiloé</a> y revisa cómo resolvimos necesidades distintas en <a href="/trabajos/survec/">SURVEC</a> y <a href="/trabajos/as-estudio/">AS_ESTUDIO</a>.</p>'}
    ], related:['/trabajos/survec/','/trabajos/as-estudio/','/guias/cuanto-cuesta-una-pagina-web/']
  },
  {
    path:'/diseno-web-chiloe/', section:'Chiloé', title:'Diseño web en Chiloé: Castro y todas sus comunas | Bergerac',
    heading:'Tu negocio en Chiloé. Su lugar en la web.',
    description:'Diseño de páginas web desde Castro para negocios de las diez comunas de Chiloé: Ancud, Quellón, Chonchi, Dalcahue y todo el archipiélago. Conoce Bergerac.',
    lead:'Una página web debe ayudar a que alguien entienda tu negocio y encuentre cómo conversar contigo. Trabajamos desde Castro con empresas y profesionales que quieren construir o renovar su presencia digital en Chiloé.',
    image:'/images/chiloe.webp',imageAlt:'Ilustración de un paisaje costero del sur de Chile al atardecer',
    blocks:[
      {title:'Diez comunas, una conversación para empezar',html:`<p>Recibimos consultas de negocios de todo el archipiélago. Nuestra base está en Castro; esta cobertura no representa oficinas en cada comuna.</p><ul class="communes">${communes.map(name=>`<li>${name}</li>`).join('')}</ul><p>Si estás en Achao, tu localidad forma parte de la comuna de Quinchao. Al escribirnos, indica dónde funciona tu negocio y comparte tus canales actuales. Así podremos conocer el contexto y acordar cómo realizar la primera reunión.</p>`},
      {title:'Que se entienda tu oferta antes del primer contacto',html:'<p>Para una empresa de servicios, la web puede reunir capacidades, experiencia y proyectos que hoy están dispersos en publicaciones. Para un profesional, puede organizar un portafolio. Para un negocio que recibe visitantes, puede aclarar ubicación, características y cómo consultar disponibilidad.</p><p>La forma cambia según el objetivo. Primero definimos qué necesita saber tu cliente; después construimos el recorrido que lo lleva a esa información.</p>'},
      {title:'Qué compartir para avanzar',html:'<ol><li>La actividad de tu negocio y la comuna desde la que trabajas.</li><li>Tu sitio actual, redes o referencias, si los tienes.</li><li>La dificultad que quieres resolver: explicar servicios, mostrar proyectos o recibir consultas más claras.</li><li>Los textos, imágenes y antecedentes disponibles.</li></ol><p>No hace falta que todo esté listo. La conversación inicial sirve precisamente para ordenar el punto de partida.</p>'},
      {title:'Diseño y desarrollo con un mismo hilo',html:'<p>Quien escucha tus ideas al comienzo es también quien dirige el diseño y desarrolla el sitio hasta la entrega. El proceso reúne estudio, definición, desarrollo y ajustes contigo.</p><p><a href="/servicios/diseno-web/">Revisa cómo trabajamos el diseño web</a>. Si tu negocio está vinculado al turismo, nuestra <a href="/guias/pagina-web-alojamiento-chiloe/">guía de páginas para alojamientos</a> puede ayudarte a preparar el contenido.</p>'}
    ],related:['/servicios/diseno-web/','/trabajos/survec/','/guias/pagina-web-alojamiento-chiloe/']
  },
  {
    path:'/trabajos/survec/',section:'Trabajo / 01',title:'SURVEC: una web para comunicar capacidad técnica | Bergerac',heading:'Precisión técnica. Comunicación clara.',
    description:'Conoce el trabajo de Bergerac para SURVEC: una página web para presentar su experiencia, capacidad técnica y conocimiento territorial con claridad.',
    lead:'SURVEC tenía experiencia, capacidad técnica y conocimiento territorial. El desafío era hacer que esa capacidad se entendiera también en su presencia digital.',
    image:'/images/survec.jpg',imageAlt:'Vista del sitio web de SURVEC, proyecto de Bergerac',
    blocks:[
      {title:'El punto de partida',html:'<p>Sus redes sociales no lograban demostrar todo lo que el negocio podía hacer. La necesidad era reunir esa información en un espacio propio y dar una lectura clara de su trabajo.</p>'},
      {title:'La respuesta',html:'<p>Construimos una página orientada a comunicar esa precisión. El sitio permite presentar a la empresa más allá de publicaciones aisladas y ofrecer una referencia a quien necesita conocerla antes de conversar.</p><p>En una web de servicios técnicos, la forma de explicar importa tanto como el aspecto visual: la persona que llega debe reconocer qué ofrece el negocio y dónde puede ampliar la información.</p>'},
      {title:'El resultado que puedes revisar',html:'<p>El sitio de SURVEC está disponible para recorrerlo. Es el resultado publicado del proyecto; aquí no atribuimos aumentos de ventas o visitas que no se hayan medido.</p><p><a class="external-link" href="https://www.survec.cl/" target="_blank" rel="noopener noreferrer">Visitar SURVEC <span aria-hidden="true">↗</span><span class="sr-only"> (abre en otra pestaña)</span></a></p>'},
      {title:'¿Tu experiencia también queda dispersa?',html:'<p>Si tus servicios y proyectos están repartidos entre redes, documentos y conversaciones, podemos revisar cómo ordenarlos en una página propia. El primer paso es entender qué necesita comprobar tu próximo cliente.</p><p><a href="/servicios/diseno-web/">Conoce nuestro servicio de diseño y desarrollo web</a>.</p>'}
    ],related:['/trabajos/as-estudio/','/servicios/diseno-web/']
  },
  {
    path:'/trabajos/as-estudio/',section:'Trabajo / 02',title:'AS_ESTUDIO: diseño de portafolio de arquitectura | Bergerac',heading:'La arquitectura, en primer plano.',
    description:'Portafolio web de AS_ESTUDIO desarrollado por Bergerac. Obras y fotografías organizadas para que la arquitectura sea protagonista.',
    lead:'AS_ESTUDIO ya tenía obras y fotografías capaces de hablar por sí solas. El desafío fue darles un orden y una presentación donde la arquitectura fuera protagonista.',
    image:'/images/as-arquitectura.jpg',imageAlt:'Vista del portafolio de arquitectura AS_ESTUDIO, proyecto de Bergerac',
    blocks:[
      {title:'El punto de partida',html:'<p>Un conjunto de buenas imágenes necesita una estructura para convertirse en un portafolio. El visitante debe poder reconocer los proyectos y recorrerlos sin que la presentación compita con las obras.</p>'},
      {title:'La respuesta',html:'<p>Construimos un portafolio para ordenar ese material y poner el trabajo arquitectónico al frente. La selección y jerarquía del contenido sostienen la experiencia: el sitio funciona como un lugar propio desde el que mostrar lo que el estudio hace.</p>'},
      {title:'Recorre el portafolio',html:'<p>El proyecto publicado permite revisar la propuesta directamente. El caso describe el trabajo realizado, sin atribuir resultados comerciales que no estén medidos.</p><p><a class="external-link" href="https://as-estudio.vercel.app/" target="_blank" rel="noopener noreferrer">Visitar AS_ESTUDIO <span aria-hidden="true">↗</span><span class="sr-only"> (abre en otra pestaña)</span></a></p>'},
      {title:'Un portafolio comienza por elegir qué mostrar',html:'<p>Para preparar una web de arquitectura, diseño u otra práctica profesional, conviene reunir los proyectos, sus imágenes y una descripción breve de cada uno. Después se puede decidir qué lugar ocupa cada trabajo y qué necesita saber quien lo visita.</p><p>Si tienes material y todavía no sabes cómo organizarlo, <a href="/servicios/diseno-web/">podemos definir contigo la estructura de tu sitio</a>.</p>'}
    ],related:['/trabajos/survec/','/servicios/diseno-web/']
  },
  {
    path:'/guias/',section:'Guías',title:'Guías para preparar la web de tu negocio | Bergerac',heading:'Antes de hacer tu web, aclaremos algunas cosas.',
    description:'Guías de Bergerac para negocios y profesionales: presupuestos web, alojamientos en Chiloé, redes sociales, dominio y correo corporativo.',
    lead:'Decisiones prácticas para preparar tu proyecto, comparar propuestas y entender qué necesita tu presencia digital. Escritas desde la forma de trabajar de Bergerac.',
    blocks:[],related:['/guias/cuanto-cuesta-una-pagina-web/','/guias/pagina-web-alojamiento-chiloe/','/guias/instagram-y-pagina-web/','/guias/dominio-hosting-correo/']
  },
  {
    path:'/guias/cuanto-cuesta-una-pagina-web/',section:'Guías / Presupuesto',title:'Cuánto cuesta una página web: qué comparar | Bergerac',heading:'El precio empieza por el alcance.',
    description:'Qué revisar al cotizar una página web en Chile: contenido, diseño, funciones, revisiones y gastos recurrentes. Una guía de Bergerac para comparar propuestas.',
    lead:'Dos presupuestos de páginas web pueden parecer comparables y cubrir trabajos muy distintos. Antes de mirar solo la cifra final, revisa qué problema resuelve cada propuesta y qué incluye la entrega.',article:true,
    blocks:[
      {title:'Por qué no hay un precio único',html:'<p>Una página breve de presentación necesita una estructura diferente a un portafolio con decenas de proyectos. Preparar textos e imágenes también toma trabajo, y las funciones especiales requieren definir qué ocurre en cada paso.</p><p>Un formulario de consulta no es lo mismo que un sistema de reservas. Mostrar productos no equivale a venderlos con pago en línea. Al cotizar, describe qué debe poder hacer el visitante.</p>'},
      {title:'Cinco puntos para comparar propuestas',html:'<ol><li><strong>Contenido:</strong> quién escribe, selecciona imágenes y carga la información.</li><li><strong>Diseño:</strong> qué se adapta y qué se desarrolla específicamente para tu negocio.</li><li><strong>Funciones:</strong> formularios, integraciones y herramientas incluidas.</li><li><strong>Revisiones:</strong> cómo se presentan avances y cómo se acuerdan los cambios.</li><li><strong>Entrega:</strong> accesos, documentación y condiciones para modificar el sitio después.</li></ol>'},
      {title:'Separar inversión inicial y gastos recurrentes',html:'<p>Además del trabajo de diseño y desarrollo, puede haber renovaciones de dominio, hosting, correo, licencias o herramientas externas. Pide que se indique quién paga cada servicio, a nombre de quién queda y con qué frecuencia se renueva.</p><p>El mantenimiento también debe definirse: qué actualizaciones cubre, cómo se solicitan y qué trabajos se cotizan por separado. No des por incluido algo que la propuesta no describe.</p>'},
      {title:'Qué enviar para recibir una cotización útil',html:'<p>Prepara una descripción del negocio, el objetivo de la página, ejemplos de contenido disponible y las funciones que consideras necesarias. Si existe una web, comparte el enlace y explica qué está fallando.</p><p>En Bergerac usamos esa conversación para proponer un alcance. No publicamos una tarifa universal porque la definición del proyecto viene primero. <a href="/servicios/diseno-web/">Conoce cómo trabajamos</a> o comparte tu punto de partida.</p>'}
    ],related:['/guias/dominio-hosting-correo/','/servicios/diseno-web/']
  },
  {
    path:'/guias/pagina-web-alojamiento-chiloe/',section:'Guías / Turismo',title:'Qué necesita una web de cabañas o alojamiento en Chiloé | Bergerac',heading:'Antes de reservar, necesitan entender el lugar.',
    description:'Cómo preparar el contenido de una página web para cabañas y alojamientos en Chiloé: ubicación, fotografías, servicios y consultas de disponibilidad.',
    lead:'Una persona que busca alojamiento necesita resolver dudas concretas: dónde está, cómo se llega, qué incluye y cómo consultar. La web puede reunir esas respuestas en un lugar que el negocio controla.',article:true,
    blocks:[
      {title:'Ubicación que ayude a planificar',html:'<p>Indica la comuna y la localidad, una ubicación verificable y orientaciones de llegada que mantengas actualizadas. Si hay condiciones de acceso relevantes, explícalas con claridad. No des tiempos exactos de traslado si no puedes sostenerlos.</p><p>En un viaje por Chiloé, conocer la ubicación ayuda a decidir si el alojamiento encaja con el recorrido. Una fotografía atractiva no reemplaza esa información.</p>'},
      {title:'Fotografías y características sin ambigüedad',html:'<p>Muestra los espacios que se ofrecen e identifica qué corresponde a cada unidad. Detalla capacidad, camas, baños, cocina, estacionamiento y servicios disponibles. Informa accesibilidad y condiciones especiales con precisión, sin hacer suposiciones.</p><p>Si las imágenes muestran una vista o un espacio compartido, descríbelo. La claridad evita que una expectativa equivocada llegue hasta la reserva.</p>'},
      {title:'Consultar disponibilidad y reservar son pasos distintos',html:'<p>Si el sitio envía una consulta, el mensaje de confirmación debe decir que la consulta fue recibida. No debe sugerir que la estadía quedó reservada. Para confirmar reservas o recibir pagos hace falta definir otro flujo y las condiciones que lo acompañan.</p><p>Un formulario de consulta puede pedir fechas, número de personas y correo de respuesta. Cada dato debe tener un propósito; evita pedir documentos personales cuando todavía no son necesarios.</p>'},
      {title:'Una lista para preparar el proyecto',html:'<ul><li>Nombre del alojamiento, comuna, ubicación y contacto.</li><li>Fotografías actuales y permiso para publicarlas.</li><li>Características y capacidad de cada unidad.</li><li>Servicios incluidos y condiciones de atención.</li><li>Proceso real para consultar, confirmar y pagar, si corresponde.</li></ul><p>Esta guía ayuda a definir el contenido; las funciones concretas se acuerdan en la propuesta. <a href="/diseno-web-chiloe/">Conoce Bergerac y nuestra cobertura en Chiloé</a>.</p>'}
    ],related:['/diseno-web-chiloe/','/guias/cuanto-cuesta-una-pagina-web/']
  },
  {
    path:'/guias/instagram-y-pagina-web/',section:'Guías / Presencia digital',title:'Instagram y página web: qué aporta cada uno | Bergerac',heading:'Tus redes y tu web pueden trabajar juntas.',
    description:'Qué función cumplen Instagram y una página web en un negocio local. Cómo organizar servicios, proyectos y contacto en una presencia digital propia.',
    lead:'Las redes permiten compartir novedades y conversar. Una página web puede dar una estructura estable a tu oferta. La decisión útil es definir qué debe resolver cada canal para tu negocio.',article:true,
    blocks:[
      {title:'La información que no debería perderse',html:'<p>Servicios, proyectos, forma de trabajar y contacto necesitan un lugar fácil de encontrar. En una secuencia de publicaciones, la persona puede tener que reconstruir esa información. Una web permite presentarla en el orden que mejor explica el negocio.</p><p>Eso no obliga a dejar de usar redes. Puedes enlazar una publicación con el caso completo o dirigir desde tu perfil a una página que aclare cómo contratar.</p>'},
      {title:'Una pregunta antes de sumar otro canal',html:'<p>¿Qué información te piden una y otra vez? Si se repiten dudas sobre lo que haces, qué incluye un servicio o dónde ver tus trabajos, tienes una pista para definir el contenido de la web.</p><p>Si el objetivo es recibir consultas, el sitio debe explicar la oferta y ofrecer una vía clara para escribir. El diseño acompaña ese recorrido.</p>'},
      {title:'Mostrar experiencia con contexto',html:'<p>Una imagen de un proyecto puede despertar interés. Un caso permite explicar el punto de partida y la solución. En <a href="/trabajos/survec/">SURVEC</a> trabajamos una presencia que comunicara experiencia y capacidad técnica; en <a href="/trabajos/as-estudio/">AS_ESTUDIO</a>, un portafolio para ordenar obras y fotografías.</p>'},
      {title:'Mantener una presencia coherente',html:'<p>Usa el mismo nombre y datos de contacto en tus canales. Revisa que los enlaces funcionen y que la información siga vigente. Es preferible una estructura clara que puedas mantener a una colección de canales desactualizados.</p><p>Para empezar, comparte tus redes, tu web si existe y la dificultad que quieres resolver. <a href="/servicios/diseno-web/">Definiremos contigo qué necesita el sitio</a>.</p>'}
    ],related:['/trabajos/survec/','/trabajos/as-estudio/']
  },
  {
    path:'/guias/dominio-hosting-correo/',section:'Guías / Lo esencial',title:'Dominio, hosting y correo corporativo: qué controlar | Bergerac',heading:'Tres piezas distintas de tu presencia digital.',
    description:'Entiende la diferencia entre dominio, hosting y correo corporativo, y qué accesos y renovaciones conviene mantener bajo control al crear una página web.',
    lead:'La dirección de tu negocio, el lugar donde funciona su web y el servicio que recibe sus correos cumplen tareas diferentes. Entender esa separación ayuda a publicar o renovar un sitio sin perder el control.',article:true,
    blocks:[
      {title:'Dominio: la dirección',html:'<p>El dominio es el nombre que una persona utiliza para llegar a tu sitio, por ejemplo el nombre de tu empresa terminado en .cl. Su registro tiene un titular y una renovación. Conviene que el negocio sepa quién lo administra y cuándo vence.</p>'},
      {title:'Hosting: dónde se sirve la web',html:'<p>El hosting permite entregar las páginas y los recursos que utiliza el sitio. Según el proyecto, también puede ejecutar funciones como un formulario. La elección depende de cómo se construye la web y qué necesita hacer.</p><p>Al recibir una propuesta, pregunta qué servicio se usará, quién lo administra y cómo se entregarán los accesos y los archivos del proyecto.</p>'},
      {title:'Correo: dónde llegan tus mensajes',html:'<p>Un correo como hola@tuempresa.cl puede funcionar con un proveedor distinto al hosting. Cambiar de sitio web no exige cambiar los buzones: hay que revisar y conservar la configuración que utiliza el correo.</p><p>Un formulario también puede enviar mensajes desde el servidor al buzón del negocio. En ese caso, el visitante no necesita abrir su aplicación de correo para realizar la consulta.</p>'},
      {title:'Qué dejar ordenado al publicar',html:'<ul><li>Titularidad y acceso al registro del dominio.</li><li>Proveedor de hosting y responsable de la cuenta.</li><li>Proveedor de correo y buzones que deben conservarse.</li><li>Fechas, responsables y costos de renovación.</li><li>Accesos al proyecto, respaldos y condiciones de soporte.</li></ul><p>No compartas contraseñas por el formulario público. Primero basta con explicar qué servicios tienes y qué cambio necesitas. <a href="/servicios/diseno-web/">Podemos revisar el punto de partida de tu nueva web</a>.</p>'}
    ],related:['/guias/cuanto-cuesta-una-pagina-web/','/servicios/diseno-web/']
  }
];
